Translated sverok_rm
There might be problems since I could not test this in an instance
since I got the error:   File
"/Users/anders/Jobb/Betahaus/Sverok/VoteIT/voteit_riksmote/rm_voteit_bui
ldout/src/voteit.core/voteit/core/models/export_import.py", line 6, in
<module>
ImportError: cannot import name IExportImport